partyrumbler/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^(?P<metro>[^/]+)/$', 'events.views.front_landing', name='home-page'),
                       url(r'^$', 'events.views.front_landing', name='home-page'),
                        url(r'^(?P<metro>[^/]+)/events/(?P<type>[^/]+)$', 'events.views.event_search', name='events-page'),
                       url(r'^(?P<metro>[^/]+)/events/(?P<type>[^/]+)/(?P<date>[^/]+)$', 'events.views.event_search', name='events-page'),
                       url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
                       url(r'^accounts/', include('allauth.urls')),
)

events/models.py
from jsonfield import JSONField
from django.contrib.gis.db import models
import collections
from autoslug import AutoSlugField
from django_extensions.db import fields as ext_fields
from djchoices import DjangoChoices, ChoiceItem
from events.utils import convert_unicode_to_string
from timezone_field import TimeZoneField
from allauth.account.models import EmailAddress
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount
import hashlib

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')

    def __unicode__(self):
        return "{}'s profile".format(self.user.username)

    class Meta:
        db_table = 'user_profile'

    def account_verified(self):
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False

    def profile_image_url(self):
        fb_uid = SocialAccount.objects.filter(user_id=self.user.id, provider='facebook')
        if len(fb_uid):
            return "http://graph.facebook.com/{}/picture?width=12&height=12".format(fb_uid[0].uid)
        return "http://www.gravatar.com/avatar/{}?s=25".format(hashlib.md5(self.user.email).hexdigest())

User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class PlaceStatus(DjangoChoices):
    # Active state means that place is visible and active checks are performed continuously
    Active = ChoiceItem("A")
    # Active_events means that place is visible only when event is present
    # otherwise it's hidden, also events screened
    Active_events = ChoiceItem("E")
    # All newly imported places automatically end up in quarantine, which means we need to asses where
    # it belongs.  Place stays in quarantine until decision is made to either move it up or down to blacklist
    # events checks performed but not visible (only to admins)
    # Checks performed every 3 days
    Quarantine = ChoiceItem("Q")
    # If place is deemed as not worthy it moves from quarantine to blacklist, we still do event checks
    # but not as often.
    # Checks performed once every X days
    Blacklist = ChoiceItem("B")
    # Pages in banned status are deemed not to be related to night clubs, no checks are performed.  Have to
    # be absolutely sure that it's no worthy.  No checks performed.
    Banned = ChoiceItem("X")

class KeywordSection(DjangoChoices):
    Body = ChoiceItem("B")
    Head = ChoiceItem("H")

class Metro(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = AutoSlugField(unique_with=['name'])
    timezone = TimeZoneField()

    def __unicode__(self):
        return self.name

class Location(models.Model):
    center = models.PointField(help_text="Represented as (longitude, latitude)", unique=True, db_index=True)
    distance = models.IntegerField(default=50000)
    metro = models.ForeignKey(Metro, null=True, blank=True, on_delete=models.CASCADE)
    objects = models.GeoManager()

    def __unicode__(self):
        metro = ''
        if self.metro:
            metro = self.metro
        return "%s %s,%s" % (metro, self.center.x, self.center.y)

class PlaceCategory(models.Model):
    fb_id = models.BigIntegerField(unique=True)
    name = models.CharField(db_index=True, max_length=20, unique=True, default='Night Club')

    def __unicode__(self):
        return self.name

class Place(models.Model):
    # Automatically create a unique id for this object
    uuid = ext_fields.UUIDField(auto=True)
    # id of facebook place
    fb_id = models.BigIntegerField(unique=True, default='7777')
    fb_search_criteria = models.CharField(max_length=100, blank=True, null=True, default=None)
    # name of facebook place
    name = models.CharField(max_length=100)
    # cached facebook data
    data = JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})
    slug = AutoSlugField(populate_from='name', unique_with='uuid', editable=True)
    added = models.DateTimeField(auto_now_add=True)
    last_status_change = models.DateTimeField(auto_now_add=True)
    point = models.PointField(help_text="Represented as (longitude, latitude)")
    status = models.CharField(db_index=True, max_length=1,
                            choices=PlaceStatus.choices,
                            default='Q')
    location = models.ForeignKey(Location, default=1, on_delete=models.CASCADE)
    category = models.ManyToManyField(PlaceCategory, blank=True, null=True, db_index=True)
    category_override = models.BooleanField(default=False)
    objects = models.GeoManager()

    def __unicode__(self):
        return "%s:%s" % (self.name, self.fb_id)

    def get_fb_search_criteria(self):
        """
            Method for retrieving fb_search_criteria field, converts name to
            ascii and strips special characters which impede fql search or
            returns fb_search_criteria field if defined
        :return:
        """
        if self.fb_search_criteria:
            return self.fb_search_criteria
        else:
            # strip unicode plus extra characters
            name = convert_unicode_to_string(self.name)
            name = name.translate(None, '|\/?><:;[]}{`~!@#$",.*%^&()-+=_')
            name = name.translate(None,"'")
            return name

class EventCategory(models.Model):
    name = models.CharField(db_index=True, max_length=20, unique=True, default='club')

    def __unicode__(self):
        return self.name

class Keyword(models.Model):
    word = models.CharField(max_length=50)
    category = models.ForeignKey(EventCategory, on_delete=models.CASCADE)
    section = models.CharField(max_length=1, choices=KeywordSection.choices, default='B')
    points = models.SmallIntegerField()



class Event(models.Model):
    fb_id = models.BigIntegerField(unique=True)
    update_time = models.PositiveIntegerField()
    # We might allow an ability to add events without tracking place in database
    # these might be one off events added by users or admins.
    # Current place attribute doesn't allow that
    place = models.ForeignKey(Place, on_delete=models.CASCADE, db_index=True)
    # cached data
    data = JSONField(load_kwargs={'object_pairs_hook': collections.OrderedDict})
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    start_date = models.DateField(db_index=True)
    name = models.TextField(db_index=True)
    description = models.TextField(null=True, blank=True)
    category = models.ManyToManyField(EventCategory, blank=True)
    category_override = models.BooleanField(default=False)
    has_profile_pic = models.BooleanField(default=False)
    objects = models.GeoManager()

    def __unicode__(self):
        return self.name

class RScore(models.Model):
    score = models.SmallIntegerField()
    category = models.ForeignKey(EventCategory, on_delete=models.PROTECT)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

events/forms.py
from django import forms
import datetime

class FrontLandingForm(forms.Form):
    date = forms.DateField(required=True, input_formats=('%B %d, %Y',), widget=forms.DateInput(format = '%B %d, %Y'), initial=datetime.date.today())
    type = forms.CharField(initial='all', widget=forms.widgets.HiddenInput())

    def get_cleaned_or_initial(self, fieldname):
        if hasattr(self, 'cleaned_data'):
            return self.cleaned_data.get(fieldname)
        else:
            return self[fieldname].field.initial

events/views.py
from django.shortcuts import render_to_response
from events.forms import FrontLandingForm
from events.models import Event, Place, Metro
from django.contrib.gis.db.models import Count
from django.template import RequestContext
from django.db.models import Q
from events.facebook import FBSearch
from facepy import exceptions
from allauth.socialaccount.models import SocialToken, SocialAccount
import pprint
from django.contrib.auth import logout, login
import datetime

def front_landing(request, metro='san_francisco'):
    # get places
    data = {
        'places' : Place.objects.filter(Q(event__category__name='club'),Q(location__metro__slug='san_francisco')).annotate(Count('event')).order_by('-event__count').distinct()[:8],
        'metros' : Metro.objects.all(),
        'metro' : Metro.objects.get(slug=metro)
    }
    if request.method == 'POST': # If the form has been submitted...
        form = FrontLandingForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            fdate = form.cleaned_data['date']
            data['type'] = form.cleaned_data['type']
            data['date'] = fdate
    else:
        form = FrontLandingForm() # An unbound form
        data['date'] = form.get_cleaned_or_initial('date')
        data['type'] = form.get_cleaned_or_initial('type')
    data['form'] = form

    events = Event.objects.filter(place__location__metro__slug=metro, has_profile_pic=True)
    equery = []
    if data['type'] == 'all' or data['type'] == 'music':
        equery.append(Q(category__name='music'))
    if data['type'] == 'all' or data['type'] == 'clubs':
        equery.append(Q(category__name='club'))
    q = equery.pop()
    for item in equery:
        q |= item
    events = events.filter(q).distinct()
    events = events.filter(start_date=data['date'])
    data['events'] = events[:9]
    if request.user.is_authenticated() and valid_token(request):
        eids = [str(event.fb_id) for event in events[:9]]
        fbsearch = FBSearch(graph_speed = 0, token = SocialToken.objects.get(account__user=request.user, account__provider='facebook') )
        jsond = fbsearch.fbgraph('SELECT name, eid, all_members_count, venue, description, start_time, end_time, \
                     update_time, hide_guest_list, pic_big, pic_cover, ticket_uri from event \
                     WHERE eid in (%s)' % ','.join(eids))
        for item in jsond['data']:
            e = events.get(fb_id=str(item['eid']))
            item['data'] = e.data
            item['place'] = e.place
            item['start_time'] = e.start_time
        data['realtime_events'] = jsond['data']
        # get friends data
        user = SocialAccount.objects.get(user=request.user)
        offset = 0
        my_friends = fbsearch.fbgraph("me?fields=friends", "get")
        counter = len(my_friends['friends']['data'])
        batch_request = []
        while counter > 0:
            pfriends = 'SELECT uid2 FROM friend WHERE uid1=%s LIMIT 20 OFFSET %s' % (user.uid, str(offset))
            the_query = 'SELECT uid, eid from event_member where uid IN (%s) AND eid in (%s)' % (pfriends, ','.join(eids))
            batch_item = {"method":"GET","relative_url":"fql?q=" + the_query}
            batch_request.append(batch_item)
            offset = offset + 20
            counter = counter - 20
        jsond = fbsearch.fbgraph(batch_request, 'batch')
        for i in jsond:
            for item in i['data']:
                for event in data['realtime_events']:
                    if str(item['eid']) == str(event['eid']):
                        if 'friends' not in event:
                            event['friends'] = []
                        event['friends'].append(item)
        elist = sorted(data['realtime_events'], key=lambda k: len(k.get("friends", [])), reverse=True)
        # if number of events is less than 9 then we need to fill up
        # all the table cells.  In the future we can throw ads
        # but for now I am just cloning whatever we have
        # if there aren't any events then tough shit!
        if len(elist) < 9 and len(elist) != 0:
            x = 0
            while True:
                try:
                    elist[x]
                except IndexError:
                    x = 0
                elist.append(elist[x])
                if len(elist) == 9:
                    break
                x = x + 1
        data['realtime_events'] = elist
    else:
        # TODO write a function to do this
        data['events'] = list(data['events'])
        if len(data['events']) < 9 and len(data['events']) != 0:
            x = 0
            while True:
                try:
                    data['events'][x]
                except IndexError:
                    x = 0
                data['events'].append(data['events'][x])
                if len(data['events']) == 9:
                    break
                x = x + 1
    return render_to_response('search_result.html', data , context_instance=RequestContext(request))

def event_search(request, metro, type='all', date=datetime.date.today()):
    data = {
        'metros' : Metro.objects.all(),
        'metro' : Metro.objects.get(slug=metro),
        'guide' : 'events',
        'date' : date,
        'type' : type,
        'dateObj': datetime.datetime.strptime(str(date), "%Y-%m-%d").date()
    }
    events = Event.objects.filter(place__location__metro__slug=metro)
    equery = []
    if data['type'] == 'all' or data['type'] == 'music':
        equery.append(Q(category__name='music'))
    if data['type'] == 'all' or data['type'] == 'clubs':
        equery.append(Q(category__name='club'))
    q = equery.pop()
    for item in equery:
        q |= item
    events = events.filter(q).distinct()
    events = events.filter(start_date=data['date'])
    data['events'] = events
    if request.user.is_authenticated() and valid_token(request):
        eids = [str(event.fb_id) for event in events]
        fbsearch = FBSearch(graph_speed = 0, token = SocialToken.objects.get(account__user=request.user, account__provider='facebook') )
        jsond = fbsearch.fbgraph('SELECT name, eid, all_members_count, venue, description, start_time, end_time, \
                     update_time, hide_guest_list, pic_big, pic_cover, ticket_uri from event \
                     WHERE eid in (%s)' % ','.join(eids))
        for item in jsond['data']:
            e = events.get(fb_id=str(item['eid']))
            item['data'] = e.data
            item['place'] = e.place
            item['start_time'] = e.start_time
        data['realtime_events'] = jsond['data']
        # get friends data
        user = SocialAccount.objects.get(user=request.user)
        offset = 0
        my_friends = fbsearch.fbgraph("me?fields=friends", "get")
        counter = len(my_friends['friends']['data'])
        batch_request = []
        while counter > 0:
            pfriends = 'SELECT uid2 FROM friend WHERE uid1=%s LIMIT 20 OFFSET %s' % (user.uid, str(offset))
            the_query = 'SELECT uid, eid from event_member where uid IN (%s) AND eid in (%s)' % (pfriends, ','.join(eids))
            batch_item = {"method":"GET","relative_url":"fql?q=" + the_query}
            batch_request.append(batch_item)
            offset = offset + 20
            counter = counter - 20
        jsond = fbsearch.fbgraph(batch_request, 'batch')
        for i in jsond:
            for item in i['data']:
                for event in data['realtime_events']:
                    if str(item['eid']) == str(event['eid']):
                        if 'friends' not in event:
                            event['friends'] = []
                        event['friends'].append(item)
        elist = sorted(data['realtime_events'], key=lambda k: len(k.get("friends", [])), reverse=True)
        data['realtime_events'] = elist
    return render_to_response('event_search.html', data , context_instance=RequestContext(request))

def valid_token(request):
    try:
        # TODO improve this, this will throw an exception if non facebook user logs in (ie isarkiso)
        fbsearch = FBSearch(graph_speed = 0, token = SocialToken.objects.get(account__user=request.user, account__provider='facebook') )
        fbsearch.fbgraph('me', 'get')
    except exceptions.OAuthError:
        # this means FB connection has failed
        logout(request)
        # TODO force login?
        return False
    except Exception:
        return False
    return True

events/templates/search_result.html
{% extends "base.html" %}


{% block container %}
    {% load jsonify %}
    {% load timetags %}

    <script type="text/javascript">
        $(function() {
            $("td[colspan=2]").find("p").hide();
            $("table").click(function(event) {
            event.stopPropagation();
            var $target = $(event.target);
            if ( $target.closest("td").attr("colspan") > 1 ) {
                $target.slideUp();
            } else {
                $target.closest("tr").next().find("p").slideToggle();
            }
        });
        });
    </script>

    <style type='text/css'>
        .carousel-inner .active.left { left: -25%; }
        .carousel-inner .next        { left:  25%; }
        .carousel-inner .prev		 { left: -25%; }
        .carousel-control 			 { width:  4%; }
        .carousel-control.left,.carousel-control.right {margin-left:15px;background-image:none;}

        .row_events:hover{ background-color: #ccc; cursor: pointer; cursor: hand; }
        .DivOverlayLayouts.com-div-generator{display:none}
        body {
        background-color:FFFFFF
        }

        .crop {
            width: 200;
            height: 162px;
            overflow: hidden;
            position: relative;
            padding-bottom: 0.5em;
            text-align:center;
            font-size:85%;
            font-weight:bold;
        }

        .crop_venue {
            width: 200px;
            height: 20px;
            overflow: hidden;
            position: relative;
            font-size:80%;
            text-align:center;
        }


        .crop_friends {
            width: 200px;
            height: 40px;
            overflow: hidden;
            position: relative;
            text-align:center;
        }

        table.etable td {
            background-color: lightgray;
            margin: 12px 12px 12px 12px;
            padding: 12px 12px 12px 12px;
        }
        table.etable {
            border-collapse: separate;
            border-spacing: 10px;
            *border-collapse: expression('separate', cellSpacing = '10px');
        }

        .contain div {
        background-color:666677;
        color:FFFFFF;
        font: 10pt Arial,Helvetica,sans-serif;
        overflow:auto
        }
        a:link, a:active, a:visited, a.navbar:link, a.navbar:active, a.navbar:visited, a.man:link, a.man:active, a.man:visited, a:hover, a.navbar:hover, a.man:hover {
        color:000000;
        font: 10pt Arial,Helvetica,sans-serif
        }
        html {
            height: 100%;
        }

        body {
            height: 100%;
        }
        .bodyContent div div form{display:inline}
        a img{border:none}
        DivOverlayLayouts.com-additional-coding{display:none}
    </style>
    <form id='myform' role="form" action="" method="post">{% csrf_token %}
    <div class="col-lg-8 ">
        <div class="col-xs-6 text-justify">
            <h4>&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-glass"></span>&nbsp;Featured Venues</h4><br>
        </div>
        <div class="col-xs-12 ">
            <div class="carousel slide" id="myCarousel">
                <div class="carousel-inner">
                    {% for place in places %}
                        {% if forloop.first %}
                            <div class="item active">
                                <div class="col-xs-3"><a href="#"><img src={{ place.data.pic|jsonify }} class="img-thumbnail" style="min-height:100px;height:100px;"></a></div>
                            </div>
                        {% else %}
                            <div class="item">
                                <div class="col-xs-3"><a href="#"><img src={{ place.data.pic|jsonify }} class="img-thumbnail" style="min-height:100px;height:100px;"></a></div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
        </div>
        <div class="col-xs-12"><br></div>
        <div class="col-xs-12">
            <div class="col-xs-4 text-left">
                <h4><span class="glyphicon glyphicon-calendar"></span>&nbsp;Events&nbsp&nbsp<a href={% url 'events-page' metro.slug 'all' %}>see more events</a></h4>
            </div>
            <div class="col-xs-4">
                <ul class="nav nav-tabs" style="float:left;">
                    {{ form.type }}
                    {% if type == 'all' %}
                        <li class="active"><a href="" class="clickClass" data-value="all">All</a></li>
                    {% else %}
                        <li><a href="" class="clickClass" data-value="all">All</a></li>
                    {% endif %}
                    {% if type == 'music' %}
                        <li class="active"><a href="" class="clickClass" data-value="music">Music</a></li>
                    {% else %}
                        <li><a href="" class="clickClass" data-value="music">Music</a></li>
                    {% endif %}
                    {% if type == 'clubs' %}
                        <li class="active"><a href="" class="clickClass" data-value="clubs">Clubs</a></li>
                    {% else %}
                        <li><a href="" class="clickClass" data-value="clubs">Clubs</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-xs-4">
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker1' data-date-format="MMMM DD, YYYY">
                        <input type='text' id="id_date" name="date" value="{{ form.date.value }}" class="form-control" />
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-xs-12">
                <br>
                <table class="etable">
                {% if realtime_events %}
                    <tr>
                    {% for event in realtime_events %}
                        <td align="top" width="200" height="230">
                            <div class="crop"><img src={{ event.data.pic_big|jsonify }} width="200" height="130" style="padding-bottom:0.5em;" />{{ event.name }}</div>
                            <div class="crop_venue">
                                {% with metro.timezone as tz %}
                                    {%  if event.start_time %}{{ event.start_time|convert_time:tz  }}{% endif %}
                                {% endwith %}
                                at {{ event.place.name }}
                            </div>
                            <div class="crop_friends">
                                {% if event.friends %}
                                    {% for friend in event.friends %}
                                        <img src="http://graph.facebook.com/{{ friend.uid }}/picture?width=15&height=15" class="img-circle" />
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </td>
                        {% if forloop.counter|divisibleby:3 %}
                            </tr>
                            <tr>
                        {% endif %}
                    {% endfor %}
                    </tr>
                {% else %}
                    <tr>
                    {% for event in events %}
                       <td align="top" width="200" height="230">
                            <div class="crop"><img src={{ event.data.pic_big|jsonify }} width="200" height="130" style="padding-bottom:0.5em;" />{{ event.name }}</div>
                            <div class="crop_venue">
                                {%  if event.start_time %}{{ event.start_time|time:"g:iA"|lower  }}{% endif %}
                                at {{ event.place.name }}
                            </div>
                            <div class="crop_friends">
                            </div>
                        </td>
                        {% if forloop.counter|divisibleby:3 %}
                            </tr>
                            <tr>
                        {% endif %}
                    {% endfor %}
                    </tr>
                {% endif %}
            </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <a class="twitter-timeline" height="1023" href="https://twitter.com/isarkisov/sf-clubs" data-widget-id="441449626671906816">Tweets from https://twitter.com/isarkisov/sf-clubs</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
    </form>

<script type="text/javascript">
    var $ = jQuery.noConflict();
    $(document).ready(function() {
         $('#myCarousel').carousel({ interval: 3000 });
            });
            $('.carousel .item').each(function(){
          var next = $(this).next();
          if (!next.length) {
            next = $(this).siblings(':first');
          }
          next.children(':first-child').clone().appendTo($(this));

          for (var i=0;i<2;i++) {
            next=next.next();
            if (!next.length) {
                next = $(this).siblings(':first');
            }

            next.children(':first-child').clone().appendTo($(this));
          }
        });
</script>
<script type="text/javascript">
    $('a.clickClass').click(function(e){
        //preventing the default link redirection
        e.preventDefault();
        $('#id_type').val($(this).data('value'));
        $(this).closest('form').submit();
    });
 </script>
<script type="text/javascript">
    $('#datetimepicker1').datepicker({
        todayHighlight: true,
        format: "MM dd, yyyy"
    }).on('changeDate', function(e){
     $('#id_date').val(e.format("MM dd, yyyy"));
      document.forms["myform"].submit();
    });
</script>
{% endblock %}